name: BeefChunkus
version: '0.1.3'
main: essie.beefchunkus.BeefChunkus
api-version: '1.20'
commands:
  beefchunkus:
    description: Give yourself a Beef Chunkus
    usage: /<command>
    permission: beefchunkus.givebeefchunkus